global:
  smtp_from: noreply@grafana.net
  smtp_hello: localhost
  smtp_smarthost: mailhog:1025

route:
  group_wait: 0s
  receiver: empty-receiver

receivers:
  # In this example we're not going to send any notification out of Alertmanager.
  - name: "empty-receiver"
