server:
  log_level: info

prometheus:
  global:
    scrape_interval: 5s
  configs:
    - name: local
      host_filter: false
      scrape_configs:
        - job_name: mimir-read-write-mode/mimir-write
          static_configs:
            - targets: ['mimir-write-1:8080', 'mimir-write-2:8080', 'mimir-write-3:8080', 'mimir-write-4:8080']
              labels:
                cluster: 'docker-compose'
                namespace: 'mimir-read-write-mode'
                container: 'mimir-write'
        - job_name: mimir-read-write-mode/mimir-read
          static_configs:
            - targets: ['mimir-read-1:8080', 'mimir-read-2:8080']
              labels:
                cluster: 'docker-compose'
                namespace: 'mimir-read-write-mode'
                container: 'mimir-read'
        - job_name: mimir-read-write-mode/mimir-backend
          static_configs:
            - targets: ['mimir-backend-1:8080', 'mimir-backend-2:8080']
              labels:
                cluster: 'docker-compose'
                namespace: 'mimir-read-write-mode'
                container: 'mimir-backend'

      remote_write:
        - url: http://mimir-write-1:8080/api/v1/push
