# This file can be used to set overrides or other runtime config.
overrides:
  anonymous:
    labels_query_optimizer_enabled: true
    ruler_evaluation_consistency_max_delay: 1m
    otel_persist_resource_attributes: true
    # Enable experimental PromQL functions for the info() function demo.
    enabled_promql_experimental_functions: all
