server:
  log_level: debug

prometheus:
  global:
    scrape_interval: 5s
    external_labels:
      scraped_by: grafana-agent
  configs:
    - name: local
      host_filter: false
      scrape_configs:
        - job_name: mimir-1
          static_configs:
            - targets: ['mimir-1:8001']
              labels:
                container: 'mimir-1'
        - job_name: mimir-2
          static_configs:
            - targets: ['mimir-2:8002']
              labels:
                container: 'mimir-2'

      remote_write:
        - url: http://mimir-1:8001/api/v1/push
          headers:
            'X-Cluster': 'development'
