# Based on information on https://opentelemetry.io/docs/collector/configuration/
receivers:
  # Data sources: traces, metrics, logs
  otlp: # Allow sending data via OTLP protocol
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Data sources: metrics
  prometheus: # Scrape self
    config:
      scrape_configs:
        - job_name: otel-collector-remote-write
          scrape_interval: 5s
          static_configs:
            - targets: [localhost:8888]
              labels:
                scraped_by: otel-collector-remote-write
        - job_name: mimir-1
          static_configs:
            - targets: ['mimir-1:8001']
              labels:
                container: 'mimir-1'
                scraped_by: otel-collector-remote-write
        - job_name: mimir-2
          static_configs:
            - targets: ['mimir-2:8002']
              labels:
                container: 'mimir-2'
                scraped_by: otel-collector-remote-write

processors:
  batch:

exporters:
  debug:
    verbosity: basic
  prometheusremotewrite:
    endpoint: http://mimir-1:8001/api/v1/push

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [debug, prometheusremotewrite]
