global:
  scrape_interval: 5s
  external_labels:
    scraped_by: prometheus

scrape_configs:
  - job_name: mimir-1
    static_configs:
      - targets: ['mimir-1:8001']
        labels:
          container: 'mimir-1'
    always_scrape_classic_histograms: true
  - job_name: mimir-2
    static_configs:
      - targets: ['mimir-2:8002']
        labels:
          container: 'mimir-2'
    always_scrape_classic_histograms: true

remote_write:
  - url: http://mimir-1:8001/api/v1/push
    send_native_histograms: true
    protobuf_message: "io.prometheus.write.v2.Request"

