{{- if .Values.ruler.remoteEvaluationDedicatedQueryPath }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "ruler-query-scheduler") }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "ruler-query-scheduler") | nindent 4 }}
    prometheus.io/service-monitor: "false"
    {{- with .Values.ruler_query_scheduler.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.ruler_query_scheduler.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ include "mimir.serverHttpListenPort" .}}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ include "mimir.serverGrpcListenPort" . }}
      protocol: TCP
      name: grpc
      targetPort: grpc
    {{- if .Values.ruler_query_scheduler.service.extraPorts }}
    {{- toYaml .Values.ruler_query_scheduler.service.extraPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "mimir.selectorLabels" (dict "ctx" . "component" "ruler-query-scheduler") | nindent 4 }}
{{- end }}
