"services":
  "memcached":
    "image": "memcached:1.6.19-alpine"
  "mimir-backend-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=backend"
      - "-activity-tracker.filepath=/activity/mimir-backend-1"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-backend-1"
    "image": "mimir"
    "ports":
      - "8006:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "mimir-backend-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=backend"
      - "-activity-tracker.filepath=/activity/mimir-backend-2"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-backend-2"
    "image": "mimir"
    "ports":
      - "8007:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "mimir-read-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=read"
      - "-activity-tracker.filepath=/activity/mimir-read-1"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-read-1"
    "image": "mimir"
    "ports":
      - "8004:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "mimir-read-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=read"
      - "-activity-tracker.filepath=/activity/mimir-read-2"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-read-2"
    "image": "mimir"
    "ports":
      - "8005:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "mimir-write-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=write"
      - "-activity-tracker.filepath=/activity/mimir-write-1"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-write-1"
    "image": "mimir"
    "ports":
      - "8001:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
      - ".data-mimir-write-1:/data:delegated"
  "mimir-write-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=write"
      - "-activity-tracker.filepath=/activity/mimir-write-2"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-write-2"
    "image": "mimir"
    "ports":
      - "8002:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
      - ".data-mimir-write-2:/data:delegated"
  "mimir-write-3":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=write"
      - "-activity-tracker.filepath=/activity/mimir-write-3"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-write-3"
    "image": "mimir"
    "ports":
      - "8003:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
      - ".data-mimir-write-3:/data:delegated"
  "minio":
    "command":
      - "server"
      - "--console-address"
      - ":9001"
      - "/data"
    "environment":
      - "MINIO_ROOT_USER=mimir"
      - "MINIO_ROOT_PASSWORD=supersecret"
    "image": "minio/minio"
    "ports":
      - "9000:9000"
      - "9001:9001"
    "volumes":
      - ".data-minio:/data:delegated"
  "nginx":
    "environment":
      - "NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx"
      - "DISTRIBUTOR_HOST=mimir-write-1:8080"
      - "ALERT_MANAGER_HOST=mimir-backend-1:8080"
      - "RULER_HOST=mimir-backend-1:8080"
      - "QUERY_FRONTEND_HOST=mimir-read-1:8080"
      - "COMPACTOR_HOST=mimir-backend-1:8080"
    "hostname": "nginx"
    "image": "nginxinc/nginx-unprivileged:1.22-alpine"
    "ports":
      - "8080:8080"
    "volumes":
      - "../common/config:/etc/nginx/templates"
"version": "3.4"
