{{- if and .Values.querier.enabled .Values.querier.kedaAutoscaling.enabled (not .Values.federation_frontend.disableOtherComponents) }}
{{- if not .Values.query_scheduler.enabled }}
{{- fail "KEDA autoscaling for querier requires query scheduler to be enabled" }}
{{- end }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "querier") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "querier") | nindent 4 }}
  annotations:
    {{- toYaml .Values.querier.annotations | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      {{- with .Values.querier.kedaAutoscaling.behavior }}
      behavior:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  maxReplicaCount: {{ .Values.querier.kedaAutoscaling.maxReplicaCount }}
  minReplicaCount: {{ .Values.querier.kedaAutoscaling.minReplicaCount }}
  pollingInterval: {{ .Values.kedaAutoscaling.pollingInterval }}
  scaleTargetRef:
    name: {{ include "mimir.resourceName" (dict "ctx" . "component" "querier") }}
    apiVersion: apps/v1
    kind: Deployment
  triggers:
  - metadata:
      {{- if .Values.kedaAutoscaling.authentication.enabled }}
      authModes: "{{ .Values.kedaAutoscaling.authentication.authModes }}"
      {{- end }}
      query: sum(max_over_time(cortex_query_scheduler_inflight_requests{container="query-scheduler",namespace="{{ .Release.Namespace }}",quantile="0.5",{{ include "toPromQLLabelSelector" .Values.kedaAutoscaling.toPromQLLabelSelector }}}[1m]))
      serverAddress: {{ include "mimir.kedaPrometheusAddress" (dict "ctx" $) }}
      threshold: {{ .Values.querier.kedaAutoscaling.querySchedulerInflightRequestsThreshold | quote }}
      {{- if .Values.kedaAutoscaling.customHeaders }}
      customHeaders: {{ (include "mimir.lib.mapToCSVString" (dict "map" .Values.kedaAutoscaling.customHeaders)) | quote }}
      {{- end }}
      ignoreNullValues: "{{ .Values.kedaAutoscaling.ignoreNullValues }}"
      unsafeSsl: "{{ .Values.kedaAutoscaling.unsafeSsl }}"
    name: cortex_querier_hpa_default
    type: prometheus
    {{- if .Values.kedaAutoscaling.authentication.enabled }}
    authenticationRef:
        name: "keda-triggger-auth"
    {{- end }}
  - metadata:
      {{- if .Values.kedaAutoscaling.authentication.enabled }}
      authModes: "{{ .Values.kedaAutoscaling.authentication.authModes }}"
      {{- end }}
      query: sum(rate(cortex_querier_request_duration_seconds_sum{container="querier",namespace="{{ .Release.Namespace }}",{{ include "toPromQLLabelSelector" .Values.kedaAutoscaling.toPromQLLabelSelector }}}[1m]))
      serverAddress: {{ include "mimir.kedaPrometheusAddress" (dict "ctx" $) }}
      threshold: {{ .Values.querier.kedaAutoscaling.querySchedulerInflightRequestsThreshold | quote }}
      {{- if .Values.kedaAutoscaling.customHeaders }}
      customHeaders: {{ (include "mimir.lib.mapToCSVString" (dict "map" .Values.kedaAutoscaling.customHeaders)) | quote }}
      {{- end }}
      ignoreNullValues: "{{ .Values.kedaAutoscaling.ignoreNullValues }}"
      unsafeSsl: "{{ .Values.kedaAutoscaling.unsafeSsl }}"
    name: cortex_querier_hpa_default_requests_duration
    type: prometheus
    {{- if .Values.kedaAutoscaling.authentication.enabled }}
    authenticationRef:
        name: "keda-triggger-auth"
    {{- end }}
  {{- $autoscaling := .Values.querier.kedaAutoscaling -}}
  {{- if .Values.querier.kedaAutoscaling.predictiveScalingEnabled }}
  - metadata:
      query: sum(max_over_time(cortex_query_scheduler_inflight_requests{container="query-scheduler",namespace="{{ .Release.Namespace }}",quantile="0.5",{{ include "toPromQLLabelSelector" .Values.kedaAutoscaling.toPromQLLabelSelector }}}[{{$autoscaling.predictiveScalingLookback}}] offset {{$autoscaling.predictiveScalingPeriod}}))
      serverAddress: {{ include "mimir.kedaPrometheusAddress" (dict "ctx" $) }}
      threshold: {{ $autoscaling.querySchedulerInflightRequestsThreshold | quote }}
      {{- if .Values.kedaAutoscaling.customHeaders }}
      customHeaders: {{ (include "mimir.lib.mapToCSVString" (dict "map" .Values.kedaAutoscaling.customHeaders)) | quote }}
      {{- end }}
      ignoreNullValues: "{{ .Values.kedaAutoscaling.ignoreNullValues }}"
      unsafeSsl: "{{ .Values.kedaAutoscaling.unsafeSsl }}"
    name: cortex_querier_hpa_default_predictive
    type: prometheus
    {{- if .Values.kedaAutoscaling.authentication.enabled }}
    authenticationRef:
        name: "keda-triggger-auth"
    {{- end }}
  {{- end }}
{{- end }}
