apiVersion: v1
kind: Service
metadata:
  name: {{ template "mimir.fullname" . }}-querier
  labels:
    app: {{ template "mimir.name" . }}-querier
    chart: {{ template "mimir.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.querier.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.querier.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.server.http_listen_port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ .Values.config.server.grpc_listen_port }}
      protocol: TCP
      name: grpc
      targetPort: grpc
  selector:
    app: {{ template "mimir.name" . }}-querier
    release: {{ .Release.Name }}
