{{- if and .Values.query_scheduler.enabled (not .Values.federation_frontend.disableOtherComponents) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "query-scheduler") }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "query-scheduler") | nindent 4 }}
    {{- with .Values.query_scheduler.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.query_scheduler.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.query_scheduler.service.type }}
  {{- if semverCompare ">= 1.22-0" (include "mimir.kubeVersion" .) }}
  internalTrafficPolicy: {{ .Values.query_scheduler.service.internalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ include "mimir.serverHttpListenPort" .}}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: {{ include "mimir.serverGrpcListenPort" . }}
      protocol: TCP
      name: grpc
      targetPort: grpc
    {{- if .Values.query_scheduler.service.extraPorts }}
    {{- toYaml .Values.query_scheduler.service.extraPorts | nindent 4 }}
    {{- end }}
  selector:
    {{- include "mimir.selectorLabels" (dict "ctx" . "component" "query-scheduler") | nindent 4 }}
{{- end }}
