{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.gatewayFullname" . }}
  labels:
    app: {{ include "mimir.name" . }}-gateway
    chart: {{ include "mimir.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- toYaml .Values.gateway.annotations | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  {{- with .Values.gateway.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if and (eq "LoadBalancer" .Values.gateway.service.type) .Values.gateway.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gateway.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      {{- if and (eq "NodePort" .Values.gateway.service.type) .Values.gateway.service.nodePort }}
      nodePort: {{ .Values.gateway.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    app: {{ include "mimir.name" . }}-gateway
    release: {{ .Release.Name }}
{{- end }}
