apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "store-gateway") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "store-gateway" "memberlist" true) | nindent 4 }}
  annotations:
    {{- toYaml .Values.store_gateway.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.store_gateway.replicas }}
  selector:
    matchLabels:
      {{- include "mimir.selectorLabels" (dict "ctx" . "component" "store-gateway" "memberlist" true) | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.store_gateway.strategy | nindent 4 }}
  serviceName: {{ template "mimir.fullname" . }}-store-gateway{{- if not .Values.enterprise.legacyLabels -}}-headless{{- end -}}
  {{- if .Values.store_gateway.persistentVolume.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: storage
        {{- if .Values.store_gateway.persistentVolume.annotations }}
        annotations:
          {{ toYaml .Values.store_gateway.persistentVolume.annotations | nindent 10 }}
        {{- end }}
      spec:
        {{- if .Values.store_gateway.persistentVolume.storageClass }}
        {{- if (eq "-" .Values.store_gateway.persistentVolume.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.store_gateway.persistentVolume.storageClass }}"
        {{- end }}
        {{- end }}
        accessModes:
          {{ toYaml .Values.store_gateway.persistentVolume.accessModes | nindent 10 }}
        resources:
          requests:
            storage: "{{ .Values.store_gateway.persistentVolume.size }}"
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "mimir.podLabels" (dict "ctx" . "component" "store-gateway" "memberlist" true) | nindent 8 }}
        {{- with .Values.store_gateway.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.useExternalConfig }}
        checksum/config: {{ .Values.externalConfigVersion }}
        {{- else }}
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.store_gateway.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "mimir.serviceAccountName" . }}
      {{- if .Values.store_gateway.priorityClassName }}
      priorityClassName: {{ .Values.store_gateway.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.store_gateway.securityContext | nindent 8 }}
      initContainers:
        {{- toYaml .Values.store_gateway.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.store_gateway.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.store_gateway.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.store_gateway.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.store_gateway.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          secret:
            secretName: {{ tpl .Values.externalConfigSecretName . }}
        {{- if .Values.enterprise.enabled }}
        - name: license
          secret:
            secretName: {{ tpl .Values.license.secretName . }}
        {{- end }}
        - name: runtime-config
          configMap:
            name: {{ template "mimir.fullname" . }}-runtime
        {{- if not .Values.store_gateway.persistentVolume.enabled }}
        - name: storage
          emptyDir: {}
        {{- end }}
        {{- if .Values.store_gateway.extraVolumes }}
        {{ toYaml .Values.store_gateway.extraVolumes | nindent 8 }}
        {{- end }}
      containers:
        {{- if .Values.store_gateway.extraContainers }}
        {{ toYaml .Values.store_gateway.extraContainers | nindent 8 }}
        {{- end }}
        - name: store-gateway
          image: "{{ include "mimir.imageReference" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=store-gateway"
            - "-config.expand-env=true"
            - "-config.file=/etc/mimir/mimir.yaml"
            {{- range $key, $value := .Values.store_gateway.extraArgs }}
            - "-{{ $key }}={{ $value }}"
            {{- end }}
          volumeMounts:
            {{- if .Values.store_gateway.extraVolumeMounts }}
            {{ toYaml .Values.store_gateway.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /etc/mimir
            {{- if .Values.enterprise.enabled }}
            - name: license
              mountPath: /license
            {{- end }}
            - name: runtime-config
              mountPath: /var/{{ include "mimir.name" . }}
            - name: storage
              mountPath: "/data"
              {{- if .Values.store_gateway.persistentVolume.subPath }}
              subPath: {{ .Values.store_gateway.persistentVolume.subPath }}             
              {{- end }}
          ports:
            - name: http-metrics
              containerPort: {{ include "mimir.serverHttpListenPort" . }}
              protocol: TCP
            - name: grpc
              containerPort: {{ include "mimir.serverGrpcListenPort" . }}
              protocol: TCP
            - name: memberlist
              containerPort: {{ include "mimir.memberlistBindPort" . }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.store_gateway.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.store_gateway.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.store_gateway.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
          env:
            {{- with .Values.global.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.store_gateway.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.global.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.store_gateway.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
