kind: MimirConfig
apiVersion: grafana.com/v1alpha1
metadata:
  name: not-important
config:
  ingester:
    ring:
      instance_availability_zone:
      num_tokens:
      heartbeat_period:
      heartbeat_timeout:
      readiness_check_ring_health:
      unregister_on_shutdown:
  distributor:
    ha_tracker:
      kvstore:
        store:
      enable_ha_tracker:
  limits:
    ruler_max_rule_groups_per_tenant:
    accept_ha_samples:
  server:
    grpc_server_max_connection_age:
    grpc_server_max_connection_age_grace:
    grpc_server_max_connection_idle:
