{{- if eq .Values.deploymentMode "microservices" }}
{{- if and .Values.gateway.enabled .Values.gateway.nginx.basicAuth.enabled (not .Values.gateway.nginx.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "gateway-nginx") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "gateway-nginx") | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
stringData:
  .htpasswd: |
    {{- tpl .Values.gateway.nginx.basicAuth.htpasswd $ | nindent 4 }}
{{- end -}}
{{- end }}