{{- if and .Values.enterprise.enabled .Values.graphite.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "graphite-web") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "graphite-web") | nindent 4 }}
  annotations:
    {{- toYaml .Values.graphite.web.annotations | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.graphite.web.replicas }}
  selector:
    matchLabels:
      {{- include "mimir.selectorLabels" (dict "ctx" . "component" "graphite-web") | nindent 6 }}
  strategy:
    {{- toYaml .Values.graphite.web.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "mimir.podLabels" (dict "ctx" . "component" "graphite-web") | nindent 8 }}
      annotations:
        {{- include "mimir.podAnnotations" (dict "ctx" . "component" "graphite-web") | nindent 8 }}
      namespace: {{ .Release.Namespace | quote }}
    spec:
      serviceAccountName: {{ template "mimir.serviceAccountName" . }}
      {{- if .Values.graphite.web.priorityClassName }}
      priorityClassName: {{ .Values.graphite.web.priorityClassName }}
      {{- end }}
      containers:
        - name: graphite-web
          image: "{{ .Values.graphite.web.image.repository }}:{{ .Values.graphite.web.image.tag }}"
          imagePullPolicy: {{ .Values.graphite.web.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.graphite.web.securityContext | nindent 12 }}
          env:
            - name: GRAPHITE_CLUSTER_SERVERS
              {{- if .Values.gateway.useDefaultProxyURLs }}
              value: {{ template "mimir.fullname" . }}-graphite.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" .  }}/graphite
              {{- else }}
              value: {{ template "mimir.fullname" . }}.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" .  }}/graphite
              {{- end }}
            - name: GRAPHITE_ENFORCE_INPUT_VALIDATION
              value: "true"
            - name: GRAPHITE_POOL_WORKERS
              value: "1"
            - name: GRAPHITE_POOL_WORKERS_PER_BACKEND
              value: "16"
            - name: GRAPHITE_USE_WORKER_POOL
              value: "false"
          ports:
            - name: http-metrics
              containerPort: {{ include "mimir.serverHttpListenPort" . }}
              protocol: TCP
          resources:
            {{- toYaml .Values.graphite.web.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.graphite.web.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.graphite.web.affinity | nindent 8 }}
      securityContext:
        {{- toYaml .Values.graphite.web.containerSecurityContext | nindent 8 }}
      tolerations:
        {{- toYaml .Values.graphite.web.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.graphite.web.terminationGracePeriodSeconds }}
{{- end -}}
