resources:
  - ../06-memcached
patches:
  # Minor difference: Jsonnet names service ports differently and uses numbers instead of names for targetPort
  - target:
      kind: Service
      name: 'mimir-(overrides-exporter|store-gateway|query-frontend(-headless)?|querier|ingester|ruler|distributor-headless|compactor|alertmanager-headless)'
    patch: |-
      - op: replace
        path: /spec/ports/0/name
        value: http-metrics
      - op: replace
        path: /spec/ports/0/targetPort
        value: http-metrics

  # Minor difference: Jsonnet names service ports differently and uses numbers instead of names for targetPort
  - target:
      kind: Service
      name: 'mimir-(store-gateway|query-frontend(-headless)?|querier|ingester|ruler|distributor-headless|compactor|alertmanager-headless)'
    patch: |-
      - op: replace
        path: /spec/ports/1/name
        value: grpc
      - op: replace
        path: /spec/ports/1/targetPort
        value: grpc

  # TODO(logiraptor): Helm doesn't add a grpc port to ruler
  - target:
      kind: Service
      name: 'mimir-(ruler)'
    patch: |-
      - op: remove
        path: /spec/ports/1

  # TODO(logiraptor): Helm doesn't add an http port to distributor-headless
  - target:
      kind: Service
      name: 'mimir-(distributor-headless)'
    patch: |-
      - op: remove
        path: /spec/ports/0

  # TODO(logiraptor): Helm's compactor service is not headless
  - target:
      kind: Service
      name: 'mimir-(compactor)'
    patch: |-
      - op: remove
        path: /spec/clusterIP
