# Example rules file to load to Mimir via the ruler API.
groups:
  - name: example
    rules:
      - record: up:count
        expr: count(up)

  - name: count_by_name
    rules:
      - record: total_count
        expr: count({__name__!=""})

  - name: example2
    rules:
      - alert: TooManyServices
        expr: count(up) > 1
        labels:
          severity: page
        annotations:
          summary: Too many services
