"services":
  "alertmanager-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=alertmanager -server.http-listen-port=8031 -server.grpc-listen-port=9031 -activity-tracker.filepath=/activity/alertmanager-8031 -alertmanager.web.external-url=http://localhost:8031/alertmanager -memberlist.nodename=alertmanager-1 -memberlist.bind-port=10031 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=alertmanager-1"
    "image": "mimir"
    "ports":
      - "8031:8031"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "alertmanager-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=alertmanager -server.http-listen-port=8032 -server.grpc-listen-port=9032 -activity-tracker.filepath=/activity/alertmanager-8032 -alertmanager.web.external-url=http://localhost:8032/alertmanager -memberlist.nodename=alertmanager-2 -memberlist.bind-port=10032 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=alertmanager-2"
    "image": "mimir"
    "ports":
      - "8032:8032"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "alertmanager-3":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=alertmanager -server.http-listen-port=8033 -server.grpc-listen-port=9033 -activity-tracker.filepath=/activity/alertmanager-8033 -alertmanager.web.external-url=http://localhost:8033/alertmanager -memberlist.nodename=alertmanager-3 -memberlist.bind-port=10033 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=alertmanager-3"
    "image": "mimir"
    "ports":
      - "8033:8033"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "compactor":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=compactor -server.http-listen-port=8006 -server.grpc-listen-port=9006 -activity-tracker.filepath=/activity/compactor-8006  -memberlist.nodename=compactor -memberlist.bind-port=10006 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=compactor"
    "image": "mimir"
    "ports":
      - "8006:8006"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "distributor-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=distributor -server.http-listen-port=8000 -server.grpc-listen-port=9000 -activity-tracker.filepath=/activity/distributor-8000  -memberlist.nodename=distributor -memberlist.bind-port=10000 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=distributor"
    "image": "mimir"
    "ports":
      - "8000:8000"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "distributor-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=distributor -server.http-listen-port=8001 -server.grpc-listen-port=9001 -activity-tracker.filepath=/activity/distributor-8001  -memberlist.nodename=distributor -memberlist.bind-port=10001 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=distributor"
    "image": "mimir"
    "ports":
      - "8001:8001"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "grafana-agent":
    "command":
      - "-config.file=/etc/agent-config/grafana-agent.yaml"
      - "-prometheus.wal-directory=/tmp"
    "image": "grafana/agent:v0.21.2"
    "ports":
      - "9091:9091"
    "volumes":
      - "./config:/etc/agent-config"
  "ingester-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=ingester -server.http-listen-port=8002 -server.grpc-listen-port=9002 -activity-tracker.filepath=/activity/ingester-8002  -memberlist.nodename=ingester-1 -memberlist.bind-port=10002 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=ingester-1"
    "image": "mimir"
    "ports":
      - "8002:8002"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
      - ".data-ingester-1:/tmp/mimir-tsdb-ingester:delegated"
  "ingester-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=ingester -server.http-listen-port=8003 -server.grpc-listen-port=9003 -activity-tracker.filepath=/activity/ingester-8003  -memberlist.nodename=ingester-2 -memberlist.bind-port=10003 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=ingester-2"
    "image": "mimir"
    "ports":
      - "8003:8003"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
      - ".data-ingester-2:/tmp/mimir-tsdb-ingester:delegated"
  "jaeger":
    "image": "jaegertracing/all-in-one"
    "ports":
      - "16686:16686"
      - "14268"
  "memcached":
    "image": "memcached:1.6"
  "minio":
    "command":
      - "server"
      - "/data"
    "environment":
      - "MINIO_ACCESS_KEY=mimir"
      - "MINIO_SECRET_KEY=supersecret"
    "image": "minio/minio"
    "ports":
      - "9000:9000"
    "volumes":
      - ".data-minio:/data:delegated"
  "prometheus":
    "command":
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--enable-feature=exemplar-storage"
    "image": "prom/prometheus:v2.32.1"
    "ports":
      - "9090:9090"
    "volumes":
      - "./config:/etc/prometheus"
  "purger":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=purger -server.http-listen-port=8014 -server.grpc-listen-port=9014 -activity-tracker.filepath=/activity/purger-8014  -memberlist.nodename=purger -memberlist.bind-port=10014 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=purger"
    "image": "mimir"
    "ports":
      - "8014:8014"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "querier":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=querier -server.http-listen-port=8004 -server.grpc-listen-port=9004 -activity-tracker.filepath=/activity/querier-8004 -querier.scheduler-address=query-scheduler:9011 -querier.frontend-address= -memberlist.nodename=querier -memberlist.bind-port=10004 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=querier"
    "image": "mimir"
    "ports":
      - "8004:8004"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "query-frontend":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=query-frontend -server.http-listen-port=8007 -server.grpc-listen-port=9007 -activity-tracker.filepath=/activity/query-frontend-8007 -store.max-query-length=8760h -query-frontend.scheduler-address=query-scheduler:9011 -memberlist.nodename=query-frontend -memberlist.bind-port=10007 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=query-frontend"
    "image": "mimir"
    "ports":
      - "8007:8007"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "query-scheduler":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=query-scheduler -server.http-listen-port=8011 -server.grpc-listen-port=9011 -activity-tracker.filepath=/activity/query-scheduler-8011 -store.max-query-length=8760h -memberlist.nodename=query-scheduler -memberlist.bind-port=10011 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=query-scheduler"
    "image": "mimir"
    "ports":
      - "8011:8011"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "ruler-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=ruler -server.http-listen-port=8021 -server.grpc-listen-port=9021 -activity-tracker.filepath=/activity/ruler-8021  -memberlist.nodename=ruler-1 -memberlist.bind-port=10021 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=ruler-1"
    "image": "mimir"
    "ports":
      - "8021:8021"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "ruler-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=ruler -server.http-listen-port=8022 -server.grpc-listen-port=9022 -activity-tracker.filepath=/activity/ruler-8022  -memberlist.nodename=ruler-2 -memberlist.bind-port=10022 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=ruler-2"
    "image": "mimir"
    "ports":
      - "8022:8022"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "store-gateway-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=store-gateway -server.http-listen-port=8008 -server.grpc-listen-port=9008 -activity-tracker.filepath=/activity/store-gateway-8008  -memberlist.nodename=store-gateway-1 -memberlist.bind-port=10008 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=store-gateway-1"
    "image": "mimir"
    "ports":
      - "8008:8008"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "store-gateway-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "sh"
      - "-c"
      - "sleep 3 && exec ./mimir -config.file=./config/mimir.yaml -target=store-gateway -server.http-listen-port=8009 -server.grpc-listen-port=9009 -activity-tracker.filepath=/activity/store-gateway-8009  -memberlist.nodename=store-gateway-2 -memberlist.bind-port=10009 -ingester.ring.store=memberlist -distributor.ring.store=memberlist -compactor.ring.store=memberlist -store-gateway.sharding-ring.store=memberlist -ruler.ring.store=memberlist -alertmanager.sharding-ring.store=memberlist"
    "depends_on":
      - "minio"
      - "distributor-1"
    "environment":
      - "JAEGER_AGENT_HOST=jaeger"
      - "JAEGER_AGENT_PORT=6831"
      - "JAEGER_SAMPLER_PARAM=1"
      - "JAEGER_SAMPLER_TYPE=const"
      - "JAEGER_TAGS=app=store-gateway-2"
    "image": "mimir"
    "ports":
      - "8009:8009"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
"version": "3.4"
