{{- if .Values.ruler.enabled -}}
{{- if .Values.ruler.podDisruptionBudget -}}
apiVersion: {{ include "mimir.podDisruptionBudget.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "ruler") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "ruler" "memberlist" true) | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      {{- include "mimir.selectorLabels" (dict "ctx" . "component" "ruler" "memberlist" true) | nindent 6 }}
{{ toYaml .Values.ruler.podDisruptionBudget | indent 2 }}
{{- end -}}
{{- end -}}
