# Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
kubeVersionOverride: "1.20"

metaMonitoring:
  grafanaAgent:
    metrics:
      remote:
        url: https://mimir.example.com/api/v1/push # test with setting a different remote for the monitoring

distributor:
  kedaAutoscaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    customHeaders:
      X-Scope-OrgID: tenant-1

ruler:
  kedaAutoscaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    customHeaders:
      X-Scope-OrgID: tenant-1

querier:
  kedaAutoscaling:
    enabled: true
    minReplicaCount: 2
    maxReplicaCount: 10
    pollingInterval: 10
    querySchedulerInflightRequestsThreshold: 6
    customHeaders:
      X-Scope-OrgID: tenant-1

query_frontend:
  kedaAutoscaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 10
    pollingInterval: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    customHeaders:
      X-Scope-OrgID: tenant-1
