# Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
kubeVersionOverride: "1.20"

metaMonitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    mimirRules: true
    mimirAlerts: true
  grafanaAgent:
    enabled: true
    installOperator: true
    metrics:
      # Leave the remote empty to use the default to send it to Mimir directly
      # remote: #
      additionalRemoteWriteConfigs:
        - url: https://mimir.example.com
          headers:
            X-Scope-OrgID: tenant-1
          auth:
            username: tenant-1
            passwordSecretName: my-secret
            passwordSecretKey: metrics

    logs:
      remote:
        url: https://loki.example.com
        auth:
          username: tenant-1
          passwordSecretName: my-secret
          passwordSecretKey: logs

ingester:
  zoneAwareReplication:
    enabled: false
store_gateway:
  zoneAwareReplication:
    enabled: false
rollout_operator:
  enabled: false
