# Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
kubeVersionOverride: "1.32"

extraObjects:
# Add a helm object type
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: extra-cm-{{ .Release.Name }}-object
    namespace: '{{ .Release.Namespace }}'
  data: |
    object.yml: "does-my-install-need-extra-info: true"
# Add a helm string type
- |
  kind: ConfigMap
  apiVersion: v1
  metadata:
    name: extra-cm-{{ .Release.Name }}-string
    namespace: '{{ .Release.Namespace }}'
  data: |
    string.yml: "test.extra-objects: true"
