# Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
kubeVersionOverride: "1.31"

configStorageType: Secret

enterprise:
  enabled: true

gateway:
  ingress:
    enabled: true
    labels:
      foo: bar

provisioner:
  enabled: true
  additionalTenants:
    - name: team-a
      secretNamespace: "{{ .Release.Namespace }}"
    - name: team-b
      secretNamespace: "{{ .Release.Namespace }}"
