# Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
kubeVersionOverride: "1.29"

distributor:
  revisionHistoryLimit: 3

overrides_exporter:
  revisionHistoryLimit: 3

querier:
  revisionHistoryLimit: 3

query_frontend:
  revisionHistoryLimit: 3

query_scheduler:
  revisionHistoryLimit: 3

ruler_querier:
  revisionHistoryLimit: 3

ruler_query_frontend:
  revisionHistoryLimit: 3

ruler_query_scheduler:
  revisionHistoryLimit: 3

ruler:
  revisionHistoryLimit: 3
