# Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
kubeVersionOverride: "1.20"

ruler:
  remoteEvaluationDedicatedQueryPath: true
