apiVersion: 1
datasources:
- name: Mimir
  type: prometheus
  access: proxy
  uid: mimir
  orgID: 1
  url: http://nginx:8080/prometheus
  isDefault: true
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
    - name: traceID
      datasourceUid: jaeger

- name: Mimir (query results caching disabled)
  type: prometheus
  access: proxy
  uid: mimir-no-caching
  orgID: 1
  url: http://nginx:8080/prometheus
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger
    httpHeaderName1: Cache-Control
  secureJsonData:
    httpHeaderValue1: no-store

- name: Jaeger
  type: jaeger
  access: proxy
  uid: jaeger
  orgID: 1
  url: http://jaeger:16686/

- name: federation-frontend
  type: prometheus
  access: proxy
  uid: federation-frontend
  orgID: 1
  url: http://host.docker.internal:8089/prometheus
  jsonData:
    httpHeaderName1: X-Scope-OrgID
  secureJsonData:
    httpHeaderValue1: anonymous
