global:
  scrape_interval: 5s
  external_labels:
    scraped_by: prometheus

scrape_configs:
  - job_name: ancillary-services
    static_configs:
      - targets:
          - 'memcached-exporter:9150'
          - 'load-generator:9900'
        labels:
          ha_cluster: 'prom-ha-pair'
          ha_replica: 'prom-ha-pair-2'
          namespace: 'mimir-microservices-mode'
    relabel_configs:
      - source_labels: ['__address__']
        target_label: 'pod'
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
      - source_labels: ['namespace', 'pod']
        target_label: 'job'
        separator: '/'
        regex: '(.+?)(-\d+)?'
        replacement: '${1}'
      - source_labels: ['pod']
        target_label: 'container'
        regex: '(.+?)(-\d+)?'
        replacement: '${1}'
    always_scrape_classic_histograms: true

remote_write:
  - url: http://distributor-2:8001/api/v1/push
    send_native_histograms: true
    send_exemplars: true
    headers:
      'X-Cluster': 'development'
