apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "distributor") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" . "component" "distributor" "memberlist" true) | nindent 4 }}
  annotations:
    {{- toYaml .Values.distributor.annotations | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.distributor.replicas }}
  selector:
    matchLabels:
      {{- include "mimir.selectorLabels" (dict "ctx" . "component" "distributor" "memberlist" true) | nindent 6 }}
  strategy:
    {{- toYaml .Values.distributor.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "mimir.podLabels" (dict "ctx" . "component" "distributor" "memberlist" true) | nindent 8 }}
      annotations:
        {{- include "mimir.podAnnotations" (dict "ctx" . "component" "distributor") | nindent 8 }}
      namespace: {{ .Release.Namespace | quote }}
    spec:
      serviceAccountName: {{ template "mimir.serviceAccountName" . }}
      {{- if .Values.distributor.priorityClassName }}
      priorityClassName: {{ .Values.distributor.priorityClassName }}
      {{- end }}
      securityContext:
        {{- include "mimir.lib.podSecurityContext" (dict "ctx" . "component" "distributor") | nindent 8 }}
      initContainers:
        {{- toYaml .Values.distributor.initContainers | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
        - name: distributor
          image: "{{ include "mimir.imageReference" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-target=distributor"
            - "-config.expand-env=true"
            - "-config.file=/etc/mimir/mimir.yaml"
          {{- if .Values.ingester.zoneAwareReplication.migration.enabled }}
            {{- if not .Values.ingester.zoneAwareReplication.migration.writePath }}
            - "-ingester.ring.zone-awareness-enabled=false"
            {{- end }}
            {{- if .Values.ingester.zoneAwareReplication.migration.excludeDefaultZone }}
            - "-ingester.ring.excluded-zones=zone-default"
            {{- end }}
          {{- end }}
          {{- range $key, $value := .Values.distributor.extraArgs }}
            - "-{{ $key }}={{ $value }}"
          {{- end }}
          volumeMounts:
            {{- if .Values.distributor.extraVolumeMounts }}
              {{ toYaml .Values.distributor.extraVolumeMounts | nindent 12}}
            {{- end }}
            - name: config
              mountPath: /etc/mimir
            {{- if .Values.enterprise.enabled }}
            - name: license
              mountPath: /license
            {{- end }}
            - name: runtime-config
              mountPath: /var/{{ include "mimir.name" . }}
            - name: storage
              mountPath: "/data"
              subPath: {{ .Values.distributor.persistence.subPath }}
            - name: active-queries
              mountPath: /active-query-tracker
          ports:
            - name: http-metrics
              containerPort: {{ include "mimir.serverHttpListenPort" . }}
              protocol: TCP
            - name: grpc
              containerPort: {{ include "mimir.serverGrpcListenPort" . }}
              protocol: TCP
            - name: memberlist
              containerPort: {{ include "mimir.memberlistBindPort" . }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.distributor.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.distributor.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.distributor.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.distributor.containerSecurityContext | nindent 12 }}
          env:
            {{- with .Values.global.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.distributor.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- $cpu_request := dig "requests" "cpu" nil .Values.distributor.resources }}
            {{- if $cpu_request }}
            {{- $cpu_request_doubled := include "mimir.parseCPU" (dict "value" $cpu_request) | float64 | mulf 2 | ceil }}
            - name: "GOMAXPROCS"
              value: {{ max $cpu_request_doubled 8 | toString | toYaml }}
            {{- end }}
          envFrom:
            {{- with .Values.global.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.distributor.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
{{- if .Values.distributor.extraContainers }}
{{ toYaml .Values.distributor.extraContainers | indent 8}}
{{- end }}
      nodeSelector:
        {{- toYaml .Values.distributor.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.distributor.affinity | nindent 8 }}
      {{- include "mimir.lib.topologySpreadConstraints" (dict "ctx" . "component" "distributor") | nindent 6 }}
      tolerations:
        {{- toYaml .Values.distributor.tolerations | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.distributor.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          {{- include "mimir.configVolume" . | nindent 10 }}
        {{- if .Values.enterprise.enabled }}
        - name: license
          secret:
            secretName: {{ tpl .Values.license.secretName . }}
        {{- end }}
        - name: runtime-config
          configMap:
            name: {{ template "mimir.fullname" . }}-runtime
{{- if .Values.distributor.extraVolumes }}
{{ toYaml .Values.distributor.extraVolumes | indent 8}}
{{- end }}
        - name: storage
          emptyDir: {}
        - name: active-queries
          emptyDir: {}

