{{- if and .Values.distributor.enabled (not .Values.federation_frontend.disableOtherComponents) }}
{{- include "mimir.lib.podDisruptionBudget" (dict "ctx" $ "component" "distributor" "memberlist" true) }}
{{- end }}
