name: compare-helm-with-jsonnet

on: pull_request

concurrency:
  # Cancel any running workflow for the same branch when new commits are pushed.
  # We group both by ref_name (available when CI is triggered by a push to a branch/tag)
  # and head_ref (available when CI is triggered by a PR).
  group: "${{ github.workflow }}-${{ github.ref_name }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Get build image from Makefile
        id: build_image_step
        run: echo "build_image=$(make print-build-image)" >> "$GITHUB_OUTPUT"
    outputs:
      build_image: ${{ steps.build_image_step.outputs.build_image }}

  goversion:
    runs-on: ubuntu-latest
    needs: prepare
    container: 
      image: ${{ needs.prepare.outputs.build_image }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Git Config
        run: git config --global --add safe.directory '*'
      - name: Get Go Version
        id: go-version
        run: |
          echo "version=$(make BUILD_IN_CONTAINER=false print-go-version)" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.go-version.outputs.version }}

  compare-manifests:
    runs-on: ubuntu-latest
    needs: goversion
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ needs.goversion.outputs.version }}
    - uses: helm/kind-action@v1.10.0
    - name: Download yq
      uses: dsaltares/fetch-gh-release-asset@1.1.2
      with:
        repo: 'mikefarah/yq'
        version: 'tags/v4.30.6'
        file: 'yq_linux_amd64'
        target: 'bin/yq'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Download tk
      uses: dsaltares/fetch-gh-release-asset@1.1.2
      with:
        repo: 'grafana/tanka'
        version: 'tags/v0.22.1'
        file: 'tk-linux-amd64'
        target: 'bin/tk'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Download jb
      uses: dsaltares/fetch-gh-release-asset@1.1.2
      with:
        repo: 'jsonnet-bundler/jsonnet-bundler'
        version: 'tags/v0.5.1'
        file: 'jb-linux-amd64'
        target: 'bin/jb'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Configure dependencies
      run: |
        set -e
        chmod +x $PWD/bin/yq
        chmod +x $PWD/bin/tk
        chmod +x $PWD/bin/jb
        echo $PWD/bin >> $GITHUB_PATH
        set +e
    - name: Make dependencies
      run: |
        # Make dependencies first to have their output in another step
        make operations/helm/charts/mimir-distributed/charts
        make build-jsonnet-tests
    - name: Compare manifests
      id: compare-manifests
      run: |
        ./operations/compare-helm-with-jsonnet/compare-helm-with-jsonnet.sh || (echo "Please fix the errors above and run 'make check-helm-jsonnet-diff' to validate" && false)
