name: compare-helm-with-jsonnet

on: pull_request

concurrency:
  # Cancel any running workflow for the same branch when new commits are pushed.
  # We group both by ref_name (available when CI is triggered by a push to a branch/tag)
  # and head_ref (available when CI is triggered by a PR).
  group: "${{ github.workflow }}-${{ github.ref_name }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  compare-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.4'
    - uses: helm/kind-action@v1.2.0
    - uses: frenck/action-setup-yq@a2ad11c46c5d7ba576861216963c9365b53f35bc
    - uses: dsaltares/fetch-gh-release-asset@d9376dacd30fd38f49238586cd2e9295a8307f4c
      with:
        repo: 'grafana/tanka'
        version: 'tags/v0.22.1'
        file: 'tk-linux-amd64'
        target: 'bin/tk'
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: dsaltares/fetch-gh-release-asset@d9376dacd30fd38f49238586cd2e9295a8307f4c
      with:
        repo: 'jsonnet-bundler/jsonnet-bundler'
        version: 'tags/v0.5.1'
        file: 'jb-linux-amd64'
        target: 'bin/jb'
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Configure dependencies
      run: |
        set -e
        chmod +x $PWD/bin/tk
        chmod +x $PWD/bin/jb
        echo $PWD/bin >> $GITHUB_PATH
        set +e

    - name: Compare manifests
      id: compare-manifests
      run: |
        # Make dependencies first so their output doesn't appear in the PR comment
        make operations/helm/charts/mimir-distributed/charts
        make build-jsonnet-tests

        set +e
        OUTPUT="$(./operations/compare-helm-with-jsonnet/compare-helm-with-jsonnet.sh 2>&1)"
        RC=$?
        set -e

        if [ "${RC}" -eq 0 ]; then
          echo "::set-output name=changed::false"
        else
          echo "$OUTPUT"
          # This makes a multiline output work
          # https://trstringer.com/github-actions-multiline-strings/
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=changed::true"
          echo "::set-output name=diff::$OUTPUT"
        fi

    - uses: int128/hide-comment-action@24848bfab99f16e129632e27397da999b9d1b2c0
      with:
        authors: 'github-actions[bot]'
        starts-with: '**Helm <> Jsonnet Diff**'

    - name: Create or update comment
      continue-on-error: true
      uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32
      if: ${{ steps.compare-manifests.outputs.changed == 'true' }}
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          **Helm <> Jsonnet Diff**

          :warning: A difference was detected between the Helm chart and the Jsonnet library.

          1. Use `make check-helm-jsonnet-diff` to reproduce the output locally.
          2. This test is experimental while we gather feedback about its usefulness.
          3. It does not block your PR from being merged, but we would appreciate you trying to keep feature parity between the Helm chart and Jsonnet library if possible.

          **If you get stuck on this step and the Mimir maintainers aren't able to help, feel free to merge without making this step pass and tag `@Logiraptor` so the Mimir maintainers can gather feedback later.**

          [Please see the contribution docs here for more info.](https://github.com/grafana/mimir/blob/main/docs/internal/contributing/contributing-to-helm-chart.md)

          <details>

          <summary>
          Expand to see the output
          </summary>

          Output of https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

          ```diff
          ${{ steps.compare-manifests.outputs.diff }}
          ```

          </details>
