name: Deploy pr preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    paths:
      - "docs/sources/**"

jobs:
  deploy-pr-preview:
    if: ! github.event.pull_request.head.repo.fork
    uses: grafana/writers-toolkit/.github/workflows/deploy-preview.yml@main
    with:
      sha: ${{ github.event.pull_request.head.sha }}
      branch: ${{ github.head_ref }}
      event_number: ${{ github.event.number }}
      title: ${{ github.event.pull_request.title }}
      repo: mimir
      source_directory: docs/sources/mimir
      website_directory: content/docs/mimir/latest
      relative_prefix: /docs/mimir/latest/
      index_file: true
