name: helm-weekly-release-pr

on:
  schedule:
    - cron: "0 10 * * 1-5" # 10 UTC on weekdays; if we miss published images one day, they should align the day after

  workflow_dispatch: # for manual testing

permissions: {}

jobs:
  weekly-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
      - uses: imjasonh/setup-crane@6da1ae018866400525525ce74ff892880c099987 # v0.5
      - name: Update/regenerate files
        id: update
        run: bash .github/workflows/scripts/helm-weekly-release.sh

      # This job uses "mimir-vendoring bot" instead of "github-actions bot" (secrets.GITHUB_TOKEN)
      # because any events triggered by the later don't spawn GitHub actions.
      # Refer to https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      - name: Retrieve GitHub App Credentials from Vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@a37de51f3d713a30a9e4b21bcdfbd38170020593 # get-vault-secrets/v1.3.0
        with:
          repo_secrets: |
            APP_ID=mimir-vendoring:app-id
            PRIVATE_KEY=mimir-vendoring:app-pem-key

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        with:
          # Variables generated by the previous step get-secrets
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: Release mimir-distributed Helm chart ${{ steps.update.outputs.new_chart_version }}
          body: Automated PR created by [helm-weekly-release-pr.yaml](https://github.com/grafana/mimir/blob/main/.github/workflows/helm-weekly-release-pr.yaml)
          commit-message: Update mimir-distributed chart to ${{ steps.update.outputs.new_chart_version }}
          branch: helm-chart-weekly-${{ steps.update.outputs.new_chart_version }}
          base: main
          labels: |
            helm
            helm-weekly-release
