name: helm-weekly-release-pr

on:
  schedule:
    - cron: "0 10 * * 1-5" # 10 UTC on weekdays; if we miss published images one day, they should align the day after

  workflow_dispatch: # for manual testing

permissions: {}

jobs:
  weekly-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: imjasonh/setup-crane@31b88efe9de28ae0ffa220711af4b60be9435f6e # v0.4
      - name: Update/regenerate files
        id: update
        run: bash .github/workflows/scripts/helm-weekly-release.sh

      # This job uses "mimir-vendoring bot" instead of "github-actions bot" (secrets.GITHUB_TOKEN)
      # because any events triggered by the later don't spawn GitHub actions.
      # Refer to https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      - name: Retrieve GitHub App Credentials from Vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@5d7e361bc7e0a183cde8afe9899fb7b596d2659b # get-vault-secrets-v1.2.0
        with:
          repo_secrets: |
            APP_ID=mimir-vendoring:app-id
            PRIVATE_KEY=mimir-vendoring:app-pem-key

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          # Variables generated by the previous step get-secrets
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: Release mimir-distributed Helm chart ${{ steps.update.outputs.new_chart_version }}
          body: Automated PR created by [helm-weekly-release-pr.yaml](https://github.com/grafana/mimir/blob/main/.github/workflows/helm-weekly-release-pr.yaml)
          commit-message: Update mimir-distributed chart to ${{ steps.update.outputs.new_chart_version }}
          branch: helm-chart-weekly-${{ steps.update.outputs.new_chart_version }}
          base: main
          labels: |
            helm
            helm-weekly-release
